### ISSUE TITLE
ompl::Exception

### ISSUE THREAD

**Issue by Zyhlibrary** [ZJU-FAST-Lab/GCOPTER#1]
Hi, when i use the code, after setting the goal point, the code report the error, is there a solution for this ?
terminate called after throwing an instance of 'ompl::Exception'
  what():  Direct sampling of the path-length objective requires Eigen, but this version of OMPL was compiled without Eigen support. If possible, please install Eigen and recompile OMPL. If this is not possible, you can manually create an instantiation of RejectionInfSampler to approximate the behaviour of direct informed sampling.

**Comment by whuer-mspace** [comment]
The following error occers when I use the 2D nav goal button to set the target destination, why?  any solutions? thanks!

terminate called after throwing an instance of 'ompl::Exception'
  what():  Direct sampling of the path-length objective requires Eigen, but this version of OMPL was compiled without Eigen support. If possible, please install Eigen and recompile OMPL. If this is not possible, you can manually create an instantiation of RejectionInfSampler to approximate the behaviour of direct informed sampling.
[global_planning_node-5] process has died [pid 18379, exit code -6, cmd /home/nuc/ROS/devel/lib/gcopter/global_planning __name:=global_planning_node __log:=/home/nuc/.ros/log/cca85ec0-befa-11ec-b074-38fc989acd2e/global_planning_node-5.log].
log file: /home/nuc/.ros/log/cca85ec0-befa-11ec-b074-38fc989acd2e/global_planning_node-5*.log

**Comment by davidzhangbuaa** [comment]
same problem encountered.

terminate called after throwing an instance of 'ompl::Exception'
  what():  Direct sampling of the path-length objective requires Eigen, but this version of OMPL was compiled without Eigen support. If possible, please install Eigen and recompile OMPL. If this is not possible, you can manually create an instantiation of RejectionInfSampler to approximate the behaviour of direct informed sampling.

**Comment by Xingchen0504** [comment]
same problem, how do solve it?

**Comment by Zyhlibrary** [comment]
> same problem, how do solve it?

You can try to download and install the OMPL yourself, and then recompile the project.

**Comment by Xingchen0504** [comment]
thx
its solved


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ZJU-FAST-Lab/GCOPTER"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月27日(星期四) 中午12:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ZJU-FAST-Lab/GCOPTER] ompl::Exception (Issue #1)





  
same problem, how do solve it?
  
You can try to download and install the OMPL yourself, and then recompile the project.
