### ISSUE TITLE
The trajectory planner doesn't work properly?

### ISSUE THREAD

**Issue by GChasing** [ZJU-FAST-Lab/GCOPTER#10]
The quadrotor is required to fly through the windows, but based on the gcopter planning, it bypass the wall to the endpoint. Thus, what's wrong the the trajectory planner? how to get the desired path?

The video can be found [here](https://www.youtube.com/watch?v=2Zv-4SrpnpQ)

Wish your reply and thank you very much!

**Comment by ZhepeiWang** [comment]
This is exactly how the code in the repo works. If you need large tilt angle to cross narrow gaps, see the corresponding proj https://github.com/ZJU-FAST-Lab/Fast-Racing

**Comment by GChasing** [comment]
@ZhepeiWang Thanks a lot. I found some associted code about gcopter at https://github.com/ZJU-FAST-Lab/Fast-Racing/blob/a1d086ccb6deb2993d71a5afda13fffa66567363/src/plan_manage/src/MinCoPlan_CPU.cpp#L117 - https://github.com/ZJU-FAST-Lab/Fast-Racing/blob/a1d086ccb6deb2993d71a5afda13fffa66567363/src/plan_manage/src/MinCoPlan_CPU.cpp#L124. 

It is a huge project, which may be unfriendly to the newer.  Could you share some ideas about how to show the large tilt angle 
to crosse narrow gaps, and how to insert the waypoints in the #9 (Adding the waypoints)?

Thanks again, and wish your reply!
