### ISSUE TITLE
 'ompl::Exception' && [global_planning_node-5] process has died

### ISSUE THREAD

**Issue by whuer-mspace** [ZJU-FAST-Lab/GCOPTER#4]
The following error occers when I use the 2D nav goal button to set the target destination, why? any solutions? thanks!

terminate called after throwing an instance of 'ompl::Exception'
what(): Direct sampling of the path-length objective requires Eigen, but this version of OMPL was compiled without Eigen support. If possible, please install Eigen and recompile OMPL. If this is not possible, you can manually create an instantiation of RejectionInfSampler to approximate the behaviour of direct informed sampling.
[global_planning_node-5] process has died [pid 18379, exit code -6, cmd /home/nuc/ROS/devel/lib/gcopter/global_planning __name:=global_planning_node __log:=/home/nuc/.ros/log/cca85ec0-befa-11ec-b074-38fc989acd2e/global_planning_node-5.log].
log file: /home/nuc/.ros/log/cca85ec0-befa-11ec-b074-38fc989acd2e/global_planning_node-5*.log

**Comment by Zyhlibrary** [comment]
You can try to download and install the OMPL yourself, and then recompile the project.

**Comment by whuer-mspace** [comment]
> You can try to download and install the OMPL yourself, and then recompile the project.

thank you very much

**Comment by cervonwong** [comment]
I had the same problem and downloading OMPL for ROS here https://ompl.kavrakilab.org/installation.html, deleting the ROS directory created in the example steps and repeating the steps fixed the problem
