### ISSUE TITLE
Where are the start-up items for Formation Hold and Multicopter Swarms Planning?

### ISSUE THREAD

**Issue by lgl-960709** [ZJU-FAST-Lab/GCOPTER#5]
Where are the start-up items for Formation Hold and Multicopter Swarms Planning?

**Comment by SamuraiChamploo** [comment]
The code of formation navigation has been open-sourced here: [Swarm-formation](https://github.com/ZJU-FAST-Lab/Swarm-Formation)

**Comment by lgl-960709** [comment]
> 编队导航的代码在这里是开源的：[Swarm-formation](https://github.com/ZJU-FAST-Lab/Swarm-Formation)

Thank you for your reply~
