### ISSUE TITLE
How to add the waypoint in the planning?

### ISSUE THREAD

**Issue by GChasing** [ZJU-FAST-Lab/GCOPTER#9]
It is exciting to see your excellent work.  From the source code, I want to know how to add the waypoint and the attitude for the quadrotor in the waypoint except for the starting point and end point, which makes the quadrotor flying through the given waypoint at the desired atttiude and yaw angle.

Looking for  your reply and thanks a lot.

**Comment by ZhepeiWang** [comment]
@PanNeng-ZJU Please contact him for the waypoint version.

**Comment by alibabasomeone** [comment]
@GChasing @PanNeng-ZJU @ZhepeiWang About [issues35](https://github.com/ZJU-FAST-Lab/GCOPTER/issues/35), can anyone help me? Thank you very much.
